/*
 * Copyright 2026 Open Health Stack Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dev.ohs.fhir.workflow

import dev.ohs.fhir.model.r4.CarePlan
import dev.ohs.fhir.model.r4.PlanDefinition
import dev.ohs.fhir.model.r4.Resource
import dev.ohs.fhir.workflow.expression.EvaluationContext
import dev.ohs.fhir.workflow.expression.ExpressionEvaluator
import dev.ohs.fhir.workflow.expression.ExpressionEvaluatorRouter
import dev.ohs.fhir.workflow.processor.PlanDefinitionProcessor
import kotlinx.datetime.LocalDate

/**
 * Parity facade for android-fhir's FhirOperator. generateCarePlan runs FHIRPath $apply;
 * evaluateMeasure/evaluateLibrary are CQL-only and remain unsupported (server-side).
 *
 * Pass a [resolver] to look knowledge artifacts up somewhere other than the [repository], such as a
 * FHIR NPM package cache.
 */
class FhirOperator(
  private val repository: WorkflowRepository,
  evaluator: ExpressionEvaluator = ExpressionEvaluatorRouter(),
  private val resolver: CanonicalResolver = RepositoryCanonicalResolver(repository),
) {
  private val processor = PlanDefinitionProcessor(evaluator, resolver)

  /**
   * Generates a [CarePlan] based on the provided inputs by applying the given [planDefinition].
   *
   * The actions of the plan definition are evaluated with FHIRPath; CQL is not supported.
   *
   * @param planDefinition the [PlanDefinition] to apply
   * @param subject the resource the plan definition is applied to, e.g. a
   *   [dev.ohs.fhir.model.r4.Patient]
   * @param variables named values made available to the FHIRPath expressions as `%variables`
   * @param today the date used as `today()` while evaluating the expressions
   * @return the [CarePlan] holding the requests generated by the applicable actions
   */
  suspend fun generateCarePlan(
    planDefinition: PlanDefinition,
    subject: Resource,
    variables: Map<String, Any?> = emptyMap(),
    today: LocalDate,
  ): CarePlan =
    processor.apply(
      planDefinition,
      EvaluationContext(subject = subject, variables = variables, today = today),
    )

  /**
   * Generates a [CarePlan] by resolving [planDefinitionCanonical] against the [WorkflowRepository]
   * and applying the [PlanDefinition] it points at.
   *
   * @throws IllegalArgumentException if no [PlanDefinition] matches the canonical url.
   * @see generateCarePlan
   */
  suspend fun generateCarePlan(
    planDefinitionCanonical: String,
    subject: Resource,
    variables: Map<String, Any?> = emptyMap(),
    today: LocalDate,
  ): CarePlan {
    val pd =
      resolver.resolve<PlanDefinition>(planDefinitionCanonical)
        ?: throw IllegalArgumentException("PlanDefinition not found: $planDefinitionCanonical")
    return generateCarePlan(pd, subject, variables, today)
  }

  /**
   * Measure evaluation requires CQL and is not supported by this port. Always throws; evaluate
   * measures server side instead.
   */
  fun evaluateMeasure(measureUrl: String): Nothing =
    throw NotImplementedError("Measure \$evaluate ($measureUrl) requires CQL; run it server-side.")

  /**
   * Library evaluation requires CQL and is not supported by this port. Always throws; evaluate
   * libraries server side instead.
   */
  fun evaluateLibrary(libraryUrl: String): Nothing =
    throw NotImplementedError("Library \$evaluate ($libraryUrl) requires CQL; run it server-side.")
}
